### ISSUE TITLE
Toughen up admin security

### ISSUE THREAD

**Issue by coxm** [alakajam-team/alakajam-irc#1]
Currently admins must be in the `env.admin.users` array, and require a password to issue admin commands to the bot, but:
- no user modes/permissions are checked;
- admin commands aren't rate limited.

Either address these or find a better way to secure admin commands.

**Comment by mkalam-alami** [comment]
Would it be secure enough to simply limit admin commands to OPs?

**Comment by coxm** [comment]
I think so, yeah.
