### ISSUE TITLE
Jam times are not really parsed as UTC

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam-irc#3]
I had to set the times to the server timezone to make the !hype command work properly.

Now a possibility would be to just plug the bot into https://alakajam.com/api/featuredEvent?pretty=true (and make the `countdown_formatted` formatting match the one we have here)

**Comment by coxm** [comment]
Oops! Ah, yes, using the API would be nicer :).

Could you post examples of the broken and working configs? I'd like to fix the UTC issue as we may still make use of it in the future.

**Comment by mkalam-alami** [comment]
For instance, in production I had to set up:
```
themeSelectionBegin: !utc '2017-09-08T21:00'
```
to obtain the result expected by:
```
themeSelectionBegin: !utc '2017-09-08T19:00'
```
(the server is in French = UTC+2 time)

**Comment by coxm** [comment]
@mkalam-alami I think this is fixed on master now. Thanks!
