### ISSUE TITLE
!hype vs !timeleft

### ISSUE THREAD

**Issue by timbeaudet** [alakajam-team/alakajam-irc#7]
I think these should be separate commands and discussed so with toasty earlier;

**!hype** should _always_ hype up for the next major event. Something like: "Next Major Event is _name_ on _date_  _48_days_ from now.

**!timeleft** should be implemented to state the next major deadline, be it the solo/team deadline, unranked deadline, ranking game deadline etc. If there is no "event / current deadline" then perhaps fall back onto what hype does to show when the next thing begins.

**Comment by coxm** [comment]
Thanks @timbeaudet!

I agree with all of this. I'm happy to add `!timeleft` straight away but the new `!hype` functionality will have to depend on https://github.com/alakajam-team/alakajam/issues/163.

**Comment by coxm** [comment]
The `!timeleft` command is live :smile:

**Comment by mkalam-alami** [comment]
We now have https://alakajam.com/api/event?pretty=true to support @timbeaudet's take of **!hype**
